### PR TITLE
A drink before your meal !?

### PR DESCRIPTION
**Pull request by ClaireLabonne**
Please consider including this recipe...

### CODE REVIEW

**Comment by claudiodsf** [comment]
Cannot merge. you have to fix it!

**Comment by ClaireLabonne** [comment]
can you merge now ?

**Comment by claudiodsf** [comment]
No, I'm sorry

**Comment by ClaireLabonne** [comment]
READY !!!!

**Comment by ClaireLabonne** [comment]
still READY !!

**Comment by ClaireLabonne** [comment]
hoping it is the last try

**Comment by claudiodsf** [comment]
Thank you for you effort! 🎉

**Pull request merged**
